package org.idl.tasks;


/**
* tasks/AbstractTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public interface AbstractTask extends org.omg.CORBA.portable.IDLEntity
{
  String info ();
  AbstractTask next () throws TaskException;
} // interface AbstractTask
