package org.idl.tasks;


/**
* tasks/AdderTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:37:39 PM CET
*/

public interface AdderTask extends AdderTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface AdderTask
