package org.idl.tasks;

/**
* tasks/AdderTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:37:39 PM CET
*/

public final class AdderTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public AdderTask value = null;

  public AdderTaskHolder ()
  {
  }

  public AdderTaskHolder (AdderTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdderTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdderTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdderTaskHelper.type ();
  }

}
