package org.idl.tasks;


/**
* tasks/AdderTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:37:39 PM CET
*/

public interface AdderTaskOperations  extends AbstractTask
{
  int a ();
  float b ();
  double result ();
  void result (double newResult);
} // interface AdderTaskOperations
