package org.idl.tasks;


/**
* tasks/AdderTaskPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:37:39 PM CET
*/

public abstract class AdderTaskPOA extends org.omg.PortableServer.Servant
 implements AdderTaskOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_a", new java.lang.Integer (0));
    _methods.put ("_get_b", new java.lang.Integer (1));
    _methods.put ("_get_result", new java.lang.Integer (2));
    _methods.put ("_set_result", new java.lang.Integer (3));
    _methods.put ("info", new java.lang.Integer (4));
    _methods.put ("next", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tasks/AdderTask/_get_a
       {
         int $result = (int)0;
         $result = this.a ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // tasks/AdderTask/_get_b
       {
         float $result = (float)0;
         $result = this.b ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // tasks/AdderTask/_get_result
       {
         double $result = (double)0;
         $result = this.result ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // tasks/AdderTask/_set_result
       {
         double newResult = in.read_double ();
         this.result (newResult);
         out = $rh.createReply();
         break;
       }

       case 4:  // tasks/AbstractTask/info
       {
         String $result = null;
         $result = this.info ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // tasks/AbstractTask/next
       {
         try {
           AbstractTask $result = null;
           $result = this.next ();
           out = $rh.createReply();
           AbstractTaskHelper.write (out, $result);
         } catch (TaskException $ex) {
           out = $rh.createExceptionReply ();
           TaskExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tasks/AdderTask:1.0", 
    "IDL:tasks/AbstractTask:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdderTask _this() 
  {
    return AdderTaskHelper.narrow(
    super._this_object());
  }

  public AdderTask _this(org.omg.CORBA.ORB orb) 
  {
    return AdderTaskHelper.narrow(
    super._this_object(orb));
  }


} // class AdderTaskPOA
