package org.idl.tasks;


/**
* tasks/FlipLineTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:31:28 PM CET
*/

public interface FlipLineTask extends FlipLineTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface FlipLineTask
