package org.idl.tasks;


/**
* tasks/FlipLineTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:31:28 PM CET
*/

public interface FlipLineTaskOperations  extends AbstractTask
{
  void update (Point[] flippedPolyLine, org.omg.CORBA.IntHolder lengthDifference);
} // interface FlipLineTaskOperations
