package org.idl.tasks;


/**
* tasks/InitialTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public interface InitialTaskOperations 
{
  org.idl.tasks.AbstractTask init (String email) throws TaskException;
} // interface InitialTaskOperations
