package org.idl.tasks;

/**
* tasks/InitialTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public final class InitialTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public org.idl.tasks.InitialTask value = null;

  public InitialTaskHolder ()
  {
  }

  public InitialTaskHolder (org.idl.tasks.InitialTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.idl.tasks.InitialTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.idl.tasks.InitialTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.idl.tasks.InitialTaskHelper.type ();
  }

}
