package org.idl.tasks;


/**
* tasks/InitialTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InitialTask.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public interface InitialTask extends InitialTaskOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface InitialTask
