package org.idl.tasks;


/**
* tasks/MatrixTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:48:23 PM CET
*/

public interface MatrixTaskOperations  extends AbstractTask
{
  int getMatrixItem (int row, int col) throws TaskException;
  void sendResult (int matrixDeterminant);
} // interface MatrixTaskOperations
