package org.idl.tasks;


/**
* tasks/MatrixTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:48:23 PM CET
*/

public interface MatrixTask extends MatrixTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final int matrixSize = (int)(3);
} // interface MatrixTask
