package org.idl.tasks;


/**
* tasks/Point.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:05:24 PM CET
*/

public final class Point implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Point ()
  {
  } // ctor

  public Point (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Point
