package org.idl.tasks;

/**
* tasks/PointHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:05:24 PM CET
*/

public final class PointHolder implements org.omg.CORBA.portable.Streamable
{
  public Point value = null;

  public PointHolder ()
  {
  }

  public PointHolder (Point initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PointHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PointHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PointHelper.type ();
  }

}
