package org.idl.tasks;


/**
* tasks/PolygonTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:05:24 PM CET
*/

public interface PolygonTask extends PolygonTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface PolygonTask
