package org.idl.tasks;


/**
* tasks/PolyLineHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 9:05:24 PM CET
*/

public final class PolyLineHolder implements org.omg.CORBA.portable.Streamable
{
  public Point value[] = null;

  public PolyLineHolder ()
  {
  }

  public PolyLineHolder (Point[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PolyLineHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PolyLineHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PolyLineHelper.type ();
  }

}
