package org.idl.tasks;

/**
* tasks/SimpleTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Pond�l�, 13. b�ezna 2023 14:23:37 CET
*/

public interface SimpleTask extends SimpleTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface SimpleTask
