package org.idl.tasks;


/**
* tasks/SimpleTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 4:46:42 PM CET
*/

public interface SimpleTask extends SimpleTaskOperations, AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface SimpleTask
