package org.idl.tasks;

/**
* tasks/SimpleTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Pond�l�, 13. b�ezna 2023 14:23:37 CET
*/

public final class SimpleTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public SimpleTask value = null;

  public SimpleTaskHolder ()
  {
  }

  public SimpleTaskHolder (SimpleTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SimpleTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SimpleTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SimpleTaskHelper.type ();
  }

}
