package org.idl.tasks;


/**
* tasks/SimpleTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 4:46:42 PM CET
*/

public interface SimpleTaskOperations  extends AbstractTask
{
  boolean isReady();
} // interface SimpleTaskOperations
