package org.idl.tasks;


/**
* tasks/SimpleTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Pond�l�, 13. b�ezna 2023 14:23:37 CET
*/

public interface SimpleTaskOperations  extends AbstractTask
{
  boolean isReady ();
} // interface SimpleTaskOperations
