package org.idl.tasks;


/**
* tasks/TaskException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InitialTask.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public final class TaskException extends org.omg.CORBA.UserException
{
  public String message = null;

  public TaskException ()
  {
    super(org.idl.tasks.TaskExceptionHelper.id());
  } // ctor

  public TaskException (String _message)
  {
    super(org.idl.tasks.TaskExceptionHelper.id());
    message = _message;
  } // ctor


  public TaskException (String $reason, String _message)
  {
    super(org.idl.tasks.TaskExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class TaskException
