package org.idl.tasks;

/**
* tasks/TaskExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* Monday, March 13, 2023 8:52:56 AM CET
*/

public final class TaskExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.idl.tasks.TaskException value = null;

  public TaskExceptionHolder ()
  {
  }

  public TaskExceptionHolder (org.idl.tasks.TaskException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.idl.tasks.TaskExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.idl.tasks.TaskExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.idl.tasks.TaskExceptionHelper.type ();
  }

}
